# Generated by Django 4.1.7 on 2023-04-09 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_confirmed_alter_user_address_appartment_and_more'),
        ('accounts', '0002_user_is_doctor'),
    ]

    operations = [
    ]
