# Generated by Django 4.1.7 on 2023-04-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='ПІБ')),
                ('specialization', models.CharField(max_length=150, verbose_name='Спеціалізація')),
                ('price', models.IntegerField(verbose_name='Вартість прийому')),
                ('info', models.CharField(max_length=1000, verbose_name='Інформація про лікаря')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна адреса')),
            ],
        ),
    ]
