# Generated by Django 4.1.7 on 2023-03-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
