# Generated by Django 4.1.7 on 2023-04-11 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_appointment_status'),
        ('reviews', '0003_remove_review_doctor_remove_review_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.doctor'),
        ),
    ]
