# Generated by Django 4.1.7 on 2023-04-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='courses',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Курси'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.CharField(default='', max_length=1000, verbose_name='Освіта'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='procedures_performed',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Виконувані процедури'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='info',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Загальна нформація про лікаря'),
        ),
    ]
