# Generated by Django 4.1.7 on 2023-04-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(blank=True, default='doctor_profile_photo/default_image.png', upload_to='doctor_profile_photo', verbose_name='Фото профіля'),
        ),
    ]
