# Generated by Django 4.1.7 on 2023-04-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_doctorunavailabletime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='day',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'time')},
        ),
        migrations.AddField(
            model_name='appointment',
            name='diagnosis',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Діагноз'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='examination',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Обстеження'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='medical_history',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Анамнез захворювання'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='objective_status',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name="Об'єктивний статус"),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recommendations',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Рекомендації'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_image.png', upload_to='doctors_profile_photo', verbose_name='Фото профіля'),
        ),
        migrations.AlterField(
            model_name='doctorunavailabletime',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_time', to='users.doctor'),
        ),
    ]
